<?php
require_once '../includes/session.php';
require_once '../includes/auth.php';
require_once '../includes/database.php';

$session = new SessionManager();
$session->requireLogin();
$session->requireRole('super_admin');

$auth = new Auth();
$db = Database::getInstance()->getConnection();

// Get all users with their posts
try {
    $stmt = $db->query("
        SELECT u.*, GROUP_CONCAT(up.post_name) as user_posts 
        FROM users u 
        LEFT JOIN user_posts up ON u.id = up.user_id 
        GROUP BY u.id 
        ORDER BY u.created_at DESC
    ");
    $users = $stmt->fetchAll();
    
} catch(PDOException $e) {
    // Fallback query if user_posts table doesn't exist
    try {
        $stmt = $db->query("SELECT * FROM users ORDER BY created_at DESC");
        $users = $stmt->fetchAll();
    } catch(PDOException $e2) {
        die("Error fetching users: " . $e2->getMessage());
    }
}

// Set headers for Excel download
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment; filename="MES_Users_Export_' . date('Y-m-d') . '.xls"');
header('Pragma: no-cache');
header('Expires: 0');

// Excel BOM for UTF-8
echo "\xEF\xBB\xBF";

// Start Excel content
?>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .header-row {
            background-color: #FF6600;
            color: white;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <h2>MES Society - Users Export</h2>
    <p>Generated on: <?php echo date('F j, Y g:i A'); ?></p>
    <p>Total Users: <?php echo count($users); ?></p>
    
    <table>
        <tr class="header-row">
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
            <th>SAP ID</th>
            <th>Phone</th>
            <th>Department</th>
            <th>Semester</th>
            <th>Role</th>
            <th>Posts</th>
            <th>Status</th>
            <th>Member Since</th>
            <th>Last Updated</th>
        </tr>
        <?php 
        $availablePosts = [
            'member' => 'General Member',
            'media_head' => 'Media Head',
            'event_planner' => 'Event Planner',
            'competition_head' => 'Competition Head',
            'hiring_head' => 'Hiring Head',
            'president' => 'President',
            'department_head' => 'Department Head'
        ];
        
        foreach($users as $index => $user): 
            // Convert user_posts string to array
            $userPosts = $user['user_posts'] ? explode(',', $user['user_posts']) : [];
            $postLabels = [];
            foreach($userPosts as $post) {
                $postLabels[] = $availablePosts[$post] ?? $post;
            }
        ?>
        <tr>
            <td><?php echo $index + 1; ?></td>
            <td><?php echo htmlspecialchars($user['name']); ?></td>
            <td><?php echo htmlspecialchars($user['email']); ?></td>
            <td><?php echo $user['sap_id'] ?: 'N/A'; ?></td>
            <td><?php echo $user['phone'] ?: 'N/A'; ?></td>
            <td><?php echo $user['department'] ?: 'N/A'; ?></td>
            <td><?php echo $user['semester'] ?: 'N/A'; ?></td>
            <td><?php echo ucfirst(str_replace('_', ' ', $user['role'])); ?></td>
            <td><?php echo !empty($postLabels) ? implode(', ', $postLabels) : 'No posts'; ?></td>
            <td><?php echo ucfirst($user['status']); ?></td>
            <td><?php echo date('M j, Y g:i A', strtotime($user['created_at'])); ?></td>
            <td><?php echo $user['updated_at'] ? date('M j, Y g:i A', strtotime($user['updated_at'])) : 'Never'; ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
    
    <br>
    <div style="margin-top: 20px; font-size: 12px; color: #666;">
        <strong>Note:</strong> This is an automated export from MES Society Portal.<br>
        Generated by: <?php echo $_SESSION['user_name'] ?? 'System'; ?><br>
        University of Lahore - Mechanical Engineering Society
    </div>
</body>
</html>
<?php
exit();
?>